In [2]:
import numpy as np
import time

In [3]:
size = 10_000
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seconds")

np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr**2
end = time.time()
print(f"numpy array time = {end-start} seconds")


python list time = 0.0010075569152832031 seconds
numpy array time = 0.001005411148071289 seconds


In [4]:
import sys
print(f"python list size = {sys.getsizeof(py_list)* len(py_list)} bytes")

python list size = 800560000 bytes


In [13]:
arr = np.array([1,2,3,4,5])
print(arr,type(arr),arr.dtype)

arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2,type(arr2),arr2.dtype)

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])
print(arr2D,arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int32
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U11
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]] (4, 3)


In [36]:
#create 
arr1 = np.zeros((2,3),dtype="int64")
print(arr1,arr1.shape)

arr2 = np.ones((4))
print(arr2,arr2.shape)

arr3 = np.full((2,3),100) #prefilled with val
print(arr3)

arr4 = np.eye(3) # eye is used to create identity matrix
print(arr4,arr4.shape)

arr5 = np.arange(1,10,2) #range elements
print(arr5)

arr6 = np.linspace(1,100,4)
print(arr6)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1.] (4,)
[[100 100 100]
 [100 100 100]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 3 5 7 9]
[  1.  34.  67. 100.]


In [46]:
#properties
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr,arr.shape) #dimention mxn
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr,float_arr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
9
int32
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [51]:
#Operations on array
arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshape = arr.reshape((3,2))
print(reshape,reshape.shape)

flattened = arr.flatten()
print(flattened,flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [54]:
#Indexing
arr = np.array([1,2,3,4,5])
arr2D = np.array([[1,2,3],[4,5,6]])
print(arr[0])
print(arr[3])
print(arr2D[0][2])
print(arr2D[1][1])

1
4
3
5


In [56]:
#fancy indexing
arr = np.array([1,2,3,4,5])
idx = [0,1,3]
print(arr[idx])

[1 2 4]


In [60]:
#Boolean Indexing
arr = np.array([1,2,3,4,5])
print(arr[arr >4])
print(arr[arr%2==0])
print(arr[arr%2!=0])

[5]
[2 4]
[1 3 5]


In [67]:
#Slicing
arr = np.array([1,2,3,4,5])
print(arr[1:5:2])
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [71]:
#copy vs view
nums = [1,2,3,4,5]
sub_list = nums[1:3]
print(sub_list)
print(nums)
sub_list[0] = 200
print(sub_list)
print(nums)

arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3]
print(sub_arr)
sub_arr[0] = 200
print(sub_arr)
print(arr)

[2, 3]
[1, 2, 3, 4, 5]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[  1 200   3   4   5]


In [76]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr,arr.dtype)
print(arr[0:3,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]] int32
[[2]
 [5]
 [8]]


In [86]:
#3D array

arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])#2 x 3 x 2
print(arr3D,arr3D.shape)
#indexing
print(arr3D[1,1,0])

#slicing
print(arr3D[:,0,:]) #first row form both layers
print(arr3D[:,:,0]) #first col form both layers
arr3D[:,0,:] = 99 #first row form both layers become 99
print(arr3D)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [88]:
#Vectorization
arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(arr ** 2)
print(arr+arr2)

[ 1  4  9 16 25]
[ 7  9 11 13 15]


In [92]:
#Broadcasting
print(arr+5)
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])

print(arr.shape)
print(arr2.shape)
print(arr+arr2)

[ 6  7  8  9 10]
(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [95]:
#normalization
arr = np.array([[1,2],[3,4]])
mean = np.mean(arr)
std_dev = np.std(arr)
normalized_arr = (arr-mean)/std_dev
print(normalized_arr)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
